### ISSUE TITLE
Error when there are more than 7 sampling dates in Organic Matter Table

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#20]
I just discovered this today.  I have 6 sampling dates for organic matter for Maroon Creek Club.  They are the only ones so far but I will other clients soon that will also have 6 or more sampling dates.  I receive an error message when rendering a report that has 6 or more OM sampling dates.  Here is the error message:

```
`inverse.rle()`:
! invalid 'rle' structure
Backtrace:
  1. ... %>% fontsize(i = 1, size = 11, part = "header")
 14. flextable::add_header_row(., values = c("", gsub(" ", "\n", paste(zoo::as.yearmon(unique(om_data$date_sample_submitted))))))
 15. flextable:::data_from_char(...)
 16. base::inverse.rle(...)
Called from: signal_abort(cnd)
Browse[1]> 

Quitting from lines 191-246 [unnamed-chunk-437] (report.Rmd)

Quitting from lines 289-305 [om-results] (report.Rmd)
```

If I just run the example Maroon Creek Club in the eric.R file, there is no problem at all.  If I run it with the following:

```
generate_report(.site_name = "Maroon Creek Club",
                .zip_code = 81611,
                .date_sample_submitted = "2024-06-06",
                .start_date = "2017-01-01",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = FALSE,
                .draw_beeswarm = "Yes",
                .typeface = "Lato")
```

I get the error message.  I have attached the MASTER DATABASE with up to date data so that you can try it.

One thing to note....In this particular client, normally I sample at three different depths 0-2, 2-4, 4-6 cm.  This time I only sampled 0-2 cm.  You will notice at the end of the MASTER DATABASE I put in "filler" measurements for 2-4 and 4-6 cm.  I used the number 2.  I did this because I wasn't sure if the code would work unless I put something in there.  Is there a way to code it so that if I happen to have a client that only samples at 1 particular depth (0-2 cm) and not the other 2 depths that it might show a "-" or NA or something for that particular testing date?

[MASTER_DATABASE.xlsx](https://github.com/user-attachments/files/15791846/MASTER_DATABASE.xlsx)

**Comment by torv72** [comment]
I did some further exploration on this.  I can only go back as far as 2021-01-01 for the "start_date" for Maroon Creek Club.  It works perfectly.  I just changed the MASTER DATABASE and deleted the extra 2-4 and 4-6 cm "fake" measurements to see what happened and the report actually rendered perfectly with a gray "NA".  I attached it so you could see it.  I also attached the MASTER DATABASE again with those deletions.

When I use 2020-01-01 as the "start_date" that is when I get the error message.  I had wanted to use 2017_01_01 as the "start_date" because the client had requested it for the fertilizer portion of the report.

[MASTER_DATABASE.xlsx](https://github.com/user-attachments/files/15792113/MASTER_DATABASE.xlsx)
[TORV-report_Maroon-Creek-Club_2024-06-06.docx](https://github.com/user-attachments/files/15792114/TORV-report_Maroon-Creek-Club_2024-06-06.docx)

**Comment by z3tt** [comment]
This is due to the table becoming too wide. Fortunately, that is not much of an issue (right now!) as the table will usually show only measurements for a single season. However, at some point this will pop up again once a client has 8 or more years of measurements.

Potential solutions:
* limit number of measurement dates (only show the last 7 in case it's more than that)
   * will always work but excludes information 
* decrease column width (and font size) which (I think) will allow for more columns 
  * which means we "just" increase the limit but it will pop up again
*  transpose (flip) the table so that soil levels are reported as columns and measurement dates as rows
   * no limit of measurement dates to be included as we can add x rows without getting issues
   
As the same information is shown in the trendline plots and can be accessed via the tooltips in the HTML version, we have decided that we
1. remove the percentage labels for the two last measurement dates from those plots
2. do not include the table in that case

@torv72 This is already implemented but we need to decide on the best solution for the OM table that s featured in the PDF report.

**Comment by torv72** [comment]
For the pdf version could we consider decreasing the column width and therefore get however many we can get...looking at it maybe 12, 13, maybe even more instead of the 7 that I currently get??? We then set that as a hard limit.  However, the trend lines would be able to show ALL samples.

html version has been decided on already.

**Comment by z3tt** [comment]
Okay, I'll see how many we can fit on a page with a reasonable font size. The trend line plots will always show all measurements within the specified time period.

**Comment by z3tt** [comment]
The error seems to occur because of a mismatch of column names (sampling dates) and not related to the width of the table. I have nevertheless implemented a rule that only the last 10 sampling dates. A table with 11 sampling dates might fit as well on the page but that seemed to be a less obvious limit.

If you have a client in your database that has 11+ OM sampling dates, I can test how much we can fit, also by adjusting font size and column width.

**Comment by torv72** [comment]
I don't have any 11+ OM sampling dates.  Realistically, I'm probably not going to hit that until 2026.  That would be if I included ALL sampling dates.  It will take even longer to hit 11+ OM sampling dates if I do it by season.

**Comment by z3tt** [comment]
Alright, so we are on the safe side for quite a while. I'll keep the 10 sampling dates limit and add a note to the respective code section so you can adjust it once you hit that limit. Or you could make up a dummy client that features 11+ dates to test it already, as you like.
