### ISSUE TITLE
New Error with Example Maroon Creek Club

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#35]
I know you are working on things so maybe this is why I am getting the following error.  FYI, I did do a Git pull earlier today so this is probably why I am getting this error knowing that you are working on things.  Bad habit on my part:). Interestingly, I put Snowmass Club in with its parameters and it worked perfectly.  It's just Maroon Creek Club in this particular case.

Just wanted you to be aware in case you were not.  Here are the parameters:

generate_report(.site_name = "Maroon Creek Club",
                .zip_code = 81611,
                .date_sample_submitted = "2024-06-06",
                .start_date = "2007-01-01",
                .om_seasons = "Spring",
                .warm_or_cool = "cool",
                .acid_extract = "Mehlich",
                .include_results_interpretation = FALSE,
                .include_sand_fraction = TRUE,
                .draw_beeswarm = "Yes",
                .output = "html")

This is what I get:

I have found several dates for OM data.

❓ Would you like to calculate OM accumulation rates?
Type y for yes or n for no and hit ENTER. n

✅️️ Alright, I'll skip the calculation of accumulation rates.
Error in `mutate()`:
ℹ In argument: `reference_only = case_when(...)`.
Caused by error in `case_when()`:
! Failed to evaluate the left-hand side of formula 1.
Caused by error:
! object 'date_sample_submitted' not found
Backtrace:
  1. base::source(here("aux-scripts", "om-text-automation.R"))
 15. dplyr::case_when(...)
 16. dplyr:::case_formula_evaluate(...)
 18. rlang::eval_tidy(pair$lhs, env = default_env)
Called from: signal_abort(cnd, .file)

Quitting from lines 477-491 [prepare-element-tables-and-auto-comments] (templates/setup.Rmd)

Quitting from lines 25-28 [setup] (report.Rmd)

**Comment by z3tt** [comment]
To fix #4 I had to adjust the code in that script but it was working for me with the database version back then (see in issue #4 where I was able to produce the report for the Marook Creek Club). Investigating it, I see that there are now two different sample submission dates in the data:

```
unique(all_om_longitudinal_table$date_sample_submitted)
[1] "2022-05-26 UTC" "2023-05-24 UTC"
```

This looks like a mistake to me? If it's correct and those sample submission dates can be one or multiple, we have to find a good solution as the current setup cannot handle both of these cases due to the `pivot_wider()`. But that's actually nothing I have changed so I'd expect that it would have been throwing an error even before working on the "for reference" results.

@torv72 Can you please check if that is correct and, if not, fix it in the database?

**Comment by z3tt** [comment]
Fixed, it should work with the latest updates.

**Comment by torv72** [comment]
Fixed.  Closed.
