### ISSUE TITLE
Assigning Custom value for each soil type versus the default values for other site_names 

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#37]
I noticed that when the .site_name = Maroon Creek Club I am not asked about custom values for each soil type, it is automatic unless I specify otherwise which is exactly what we wanted to do.  So that is working perfectly.   Here is a screen shot of that just for reference. 
<img width="663" alt="Screenshot 2024-09-15 at 5 08 30 PM" src="https://github.com/user-attachments/assets/58387d6b-e437-448e-88ea-c3b8a1a89844">

However, if I change the .site_name to Snowmass Club for example, I am not asked this question about default values.  Instead, I must specify each one.  Here is a screenshot of what I am seeing.  Everything still works, it is just that I have to enter each value manually versus the default that I get when I specify Maroon Creek Club.

<img width="778" alt="Screenshot 2024-09-15 at 5 09 50 PM" src="https://github.com/user-attachments/assets/9f7ce5fa-d7c4-48b4-bac4-5f314cee3195">

I'm wondering if the default values were only assigned to Maroon Creek Club????  It should be to any .site_name that is inputed.

**Comment by z3tt** [comment]
Hi Eric, this is due to the fact that it features a soil type (APPROACH) that is* not having a default value. In that case, it doesn't ask if the default values should be used as combining both the defaults plus a custom value for the other type seemed a bit confusing. But we can adjust the logic in case there is an non-default soil type. Let me know

\* To be precise it should read "was" as we have added a default value for APPROACH as well; but I missed to update the check, now it should work.

**Comment by torv72** [comment]
We can make the default value for APPROACH the same as the default value for FAIRWAY.  If there is a non-default soil type other than what we have already now specified, then it can ask me for a manual input value.

**Comment by z3tt** [comment]
The default value is already implemented, and now also asked for when APPROACH is found.
