### ISSUE TITLE
"Selection" showing up and asking for an input during rendering of report

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#6]
When I render a report for the first time I am being asked "Selction":  and having to input some sort of value before the rendering will complete.  I guessed and inputed "1" and it continued to render.  This is happening on every first run of a report that I do.  You indicated that it could be a beeswarm package behavior.  I was able to get some screenshots of what it looks like during a report rendering.

<img width="848" alt="Screenshot 2024-05-06 at 9 49 41 AM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/7f218fb8-c5fa-44d8-95c1-3dbd83ea31a1">
<img width="753" alt="Screenshot 2024-05-05 at 7 21 10 AM" src="https://github.com/torv72/torv-reports-v4/assets/90870379/b2c5748c-e444-4605-a522-e13e995eabf5">

**Comment by z3tt** [comment]
This happened to me as well now after discarding some changes (i.e. also removing some automatically generated folders). The selection dialogue pops up when there is no `figures` folder in the `report` directory and this plus all the subfolders are created. I think it's due to setting the figure root location as a global variable before creating those folders. This might be caused due to my restructuring of the codes but actually, don't think so as the relevant code is executed before rendering the report in both cases.

Anyway, it's solved by now: I moved the folder creation tep into `generate-report.R` as there is no need to keep that in the `setup.Rmd`, those folders are created anyway and do not rely on the data. I also simplified the code a bit, should all work.

Commit 440606137f2e21d9a8b2a00451078c5d79c66e55 solved the issue.
