### ISSUE TITLE
Opinion question on Required Element per Area table placement

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#69]
Wanted your opinion on the table "Element per area table". Given that we have the tiny charts in the Executive Summary (by the way I really like those) and given that the Element per area table is pretty small, do you think it would make sense to just move it into the Executive Summary underneath the bullet point that denotes "Deficits..." or " No Deficits..."?

**Comment by z3tt** [comment]
It might be a valid decision! In general, I'd be careful not to blow up the exec summary too much but in the end, it's an expert decision. I think it's a good idea to show it in case there are deficits only (otherwise it's a table full of dashes anyway), great implementation!

Related to that, I like your addition to the tiny charts. However, as it pops up every time the graphic is shown, I wonder how we could make this less repetitive (but fail to come up with a solution for now). I guess we could shorten it a bit so it maybe fits on a single line? We could also make it a footnote or title of the graphic itself, but not sure if that'd be an improvement.
