### ISSUE TITLE
Question on How to Read Trend Line Plots Legend

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#70]
Question. In the PDF version of the report, the "How to Read Trend Line Plots Legend" link below the visualizations take you to the end of the report to where the "How to Read Trend Line Plots Legend" is.  This is perfect. However, I noticed that the "green" average line for the Organic Matter visualizations is not in the "How to Read Trend Line Plots". 

As you may recall, the green line represents the "TORV average" and is used in the Organic Matter vis.  The grey line is the clients " historic average" which we have setup correctly in the soil trend line graphs.  Both work perfectly in the html version of the report.

Do we just add a green line to the "How to Read Trend Line Plots Legend" viz in the PDF version?  Whatever is easiest. 

Everything seems to be working well so far! 

Here is a completed report where you can see what I mean.

[TORV-report_The-Broadmoor-East_2024-10-15_season_average copy.pdf](https://github.com/user-attachments/files/17671248/TORV-report_The-Broadmoor-East_2024-10-15_season_average.copy.pdf)

**Comment by z3tt** [comment]
Yo are right, that is the problem of having one "how to read" chart for a set of similar, yet not identical charts. I am a bit unsure how to handle this best. I made a note in one of our issues asking how we want to treat it (but also forgot about it). 

I think there are several possible approaches here:

1. Add another line to the existing "how to" chart -- sounds fine but might get busy
2. Adjust the label (and ignore the color) -- likely not a good option as it might be confusing
3. Provide two "how to" charts, one for historic averages (non-OM charts) and one for TORV averages (OM charts) -- sounds fine but cutters the last page of the report (still okay I guess)

What would be your favorite solution? For approach 3, we could also consider moving it to the respective section instead of having a "how to read" page for all on the last page.

**Comment by torv72** [comment]
I’m leaning towards 1 OR fit into each respective section of the report.  OM and Water certainly appear to have the space. The soil section looks like it is pushing it.  If we did 1 we’d add an additional sentence explaining what the green dashed line is. I like 3 too but having two of the same legends and having to read about each one to figure out what it means seems like more work on the client’s part.

**Comment by z3tt** [comment]
I have added the line to the static legend plot. I also reduced the size of all labels in the PDF a bit and adjusted the text (just a suggestion, feel free to rephrase it). Let me know in case you need further adjustments.

![Screenshot 2024-11-11 at 17 32 05](https://github.com/user-attachments/assets/f40c1c3f-9bf3-4aea-aead-453e09e74826)
