### ISSUE TITLE
%Retained in Sand Fraction Table

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#73]
I thought we might have had this on the list but when there is only one Sand Fraction measurement the word "%Retained" is broken up.  Not sure if we can make that into one word versus %Re-tained being shown now.

<img width="566" alt="Screenshot 2024-11-16 at 11 56 24 AM" src="https://github.com/user-attachments/assets/f672e66c-28bd-42ad-84a0-0b767c523b6c">

**Comment by torv72** [comment]
Note that this is only in the PDF version. The html version looks perfect.  Forgot to mention that.

**Comment by z3tt** [comment]
We discussed this a few weeks ago. It's due to the reduced column width to allow for as many sampling dates as possible. It will be fine if you have more than 1 sampling.

If it bothers you, I can write a condition to check if it's one or multiple columns and change the width accordingly to allow for more space in such a case.

**Comment by torv72** [comment]
No worries.  Thanks for that reminder!  Good to go.
